# awesome-pages copy of YAML settings
# pages are loaded dynamically

site_name: Dimensions BigQuery Lab
docs_dir: src-docs
site_dir: ../docs

# repo_url: https://github.com/digital-science/dimensions-gbq-lab

nav:
    - Home: index.md
    - Tutorials:
        - tutorials/index.md
        - tutorials/01-connection.md
        - tutorials/03-dates.md
        - tutorials/04-nested.md
        - tutorials/02-dsl.md
        - tutorials/05-topic_clusters.md
        - tutorials/06-funder_grant_pubs.md
        - tutorials/07-retrieve_patents.md
        - tutorials/08-research_integrity.md
        - tutorials/09-orcid.md
        - tutorials/10-datacite.md
    - ...

theme:
    name: material
    favicon: assets/img/favicon.ico
    logo: assets/img/apple-touch-icon.png
    custom_dir: src-docs/custom_theme/
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
plugins:
    - search
    - awesome-pages
extra:
  analytics:
    provider: google
    property: G-BWP057HYGP
copyright: © Copyright 2021-2024 Digital Science & Research Solutions, Inc. All Rights Reserved | <a href="https://www.dimensions.ai/">About us</a> · <a href="https://www.dimensions.ai/privacy/">Privacy policy</a> · <a href="https://www.dimensions.ai/website-terms/">Legal terms</a>